
title: "nullptr security"
description: >
  nullptr security is an organization specializing in bespoke
  cybersecurity tools, techniques, and consulting. 
baseurl: ""
url: "https://nullptrsec.io"
email: "contact@nullptrsec.io"
permalink: "/posts/:title"
theme: minima
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty